name: Python CI/CD Workflow

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1

    - name: Create and Activate Conda Environment
      run: |
        conda create --name myenv python=3.10
        source activate myenv

    - name: Install dependencies
      run: |
        while read requirement; do conda install --yes $requirement || pip install $requirement; done < requirements.txt

    - name: Run Tests
      run: |
        # Add commands to run your tests here
        echo "Running tests"